default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kaopass_development

test:
  <<: *default
  database: kaopass_test

production:
  <<: *default
  database: kaopass_production
  username: kaopass
  password: <%= ENV['KAOPASS_DATABASE_PASSWORD'] %>
