aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-2
  bucket: zero-to-one-photos
  collection_id: <%= ENV['AWS_COLLECTION_ID'] %>
signature_cdn_base: https://d1z9ai696k5k24.cloudfront.net/signature